[package]
name = "strainberry"
version = "0.3.2"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["cargo", "derive"] }
edlib_rs = { git = "https://github.com/rvicedomini/edlib-rs" }
fishers_exact = "1.0.1"
flate2 = "1.1.0"
itertools = "0.15.0"
libc = "0.2.170"
needletail = "0.7.3"
rayon = "1.10.0"
rust-htslib = { version = "1.0.1", default-features = false }
spdlog-rs = "0.5.3"
spoa_rs = { git = "https://github.com/rvicedomini/spoa-rs" }
tinyvec = { version = "1.9.0", features = ["alloc"] }
which = "8.0.5"

[profile.release]
lto = true
